name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            HOSTNAME : ${{ secrets.HOSTNAME  }}
        run: |
          chmod 400 AKAJ3.pem
          scp -i AKAJ3.pem -r "infoNight" ubuntu@"$HOSTNAME":~/

  run:
      runs-on: ubuntu-latest
      needs: deploy

      steps:
      - uses: actions/checkout@v2
      - name: Launch front server
        env:
            HOSTNAME : ${{ secrets.HOSTNAME  }}
        run: |
          chmod 400 AKAJ3.pem
          ssh -i "AKAJ3.pem" ubuntu@"$HOSTNAME"'
            cd infoNight
            npm i
            pm2 start npm --name "next" -- start
          '