name: Deploy to AWS EC2

on:
  push:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}

        run: |
          chmod 400 AKAJ3.pem
          scp -i AKAJ3.pem -r "infoNight" ubuntu@ec2-3-142-240-102.us-east-2.compute.amazonaws.com:~/

  run:
      runs-on: ubuntu-latest
      needs: deploy

      steps:
      - uses: actions/checkout@v2
      - name: Launch front server
        env:
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
        run: |
          chmod 400 AKAJ3.pem
          ssh -i "AKAJ3.pem" ubuntu@ec2-3-142-240-102.us-east-2.compute.amazonaws.com '
            cd infoNight
            npm i
            pm2 start npm --name "next" -- start
          '